#!/bin/bash

# Check if the script is being run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Display Active Internet Connections (only servers)
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -tulnp | awk '
NR>1 { 
    if ($1 == "tcp" || $1 == "udp" || $1 == "tcp6" || $1 == "udp6") {
        printf "%-4s %-6s %-6s %-22s %-22s %-10s %-s\n", $1, $2, $3, $5, $6, $7, $8
    } 
}'

# Display Active UNIX domain sockets (only servers)
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
ss -xlnp | awk '
NR>1 {
    if ($1 == "unix") {
        printf "%-5s %-6s %-11s %-11s %-12s %-8s %-16s %-s\n", $1, $2, $3, $4, $5, $6, $7, $8
    } 
}'
